import React, { useState } from 'react';
import {
  Database,
  CheckCircle2,
  AlertCircle,
  Copy,
  Terminal,
  Zap,
  Shield,
  Smartphone,
  Radio,
  FileText,
  RefreshCw,
  Layers,
  ArrowRight,
  Sparkles,
  ExternalLink,
  Lock,
} from 'lucide-react';
import { PageHeader } from '../../ui/PageHeader';
import { Card } from '../../ui/Card';
import { Button } from '../../ui/Button';
import { Badge } from '../../ui/Badge';
import { useData } from '../../../context/DataContext';
import { copyToClipboard } from '../../../lib/utils';
import { soundEngine } from '../../../lib/sound';

export const SupabaseGuideView: React.FC = () => {
  const { isSupabaseLive, supabaseStatus, refreshSupabaseStatus } = useData();
  const [activeTab, setActiveTab] = useState<'readme' | 'sql' | 'realtime_checklist' | 'quick_setup'>('readme');
  const [isTesting, setIsTesting] = useState(false);
  const [copiedSection, setCopiedSection] = useState<string | null>(null);

  const handleCopy = async (text: string, sectionId: string) => {
    const ok = await copyToClipboard(text);
    if (ok) {
      setCopiedSection(sectionId);
      soundEngine.playSuccessChime();
      setTimeout(() => setCopiedSection(null), 2200);
    }
  };

  const handleTestPing = async () => {
    setIsTesting(true);
    await refreshSupabaseStatus();
    setIsTesting(false);
    soundEngine.playNotificationBeep(880, 0.2);
  };

  const sqlCode = `-- ====================================================================
-- MIGRACIÓN SUPABASE: CONJUNTOS APP (POSTGRESQL + RLS + REALTIME)
-- ====================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. TABLA: CONJUNTOS RESIDENCIALES (Multi-Tenant)
CREATE TABLE IF NOT EXISTS public.residential_complexes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(50) NOT NULL UNIQUE,
  address VARCHAR(255),
  city VARCHAR(100),
  phone VARCHAR(50),
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'blocked')),
  plan VARCHAR(20) DEFAULT 'free' CHECK (plan IN ('free', 'pro', 'enterprise')),
  subscription_status VARCHAR(20) DEFAULT 'trial' CHECK (subscription_status IN ('active', 'trial', 'blocked')),
  trial_ends_at TIMESTAMPTZ,
  current_period_end TIMESTAMPTZ,
  subscription_notes TEXT,
  payment_receipt_uploaded_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABLA: PERFILES DE USUARIO
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  role VARCHAR(50) NOT NULL CHECK (role IN ('super_admin', 'admin', 'resident', 'guard')),
  residential_complex_id BIGINT REFERENCES public.residential_complexes(id) ON DELETE SET NULL,
  requested_complex_id BIGINT REFERENCES public.residential_complexes(id) ON DELETE SET NULL,
  apartment_number VARCHAR(50),
  requested_block_or_apt VARCHAR(100),
  face_photo_path TEXT,
  phone VARCHAR(50),
  fcm_token TEXT,
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'pending', 'blocked')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABLA: TORRES Y BLOQUES
CREATE TABLE IF NOT EXISTS public.apartment_blocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  residential_complex_id BIGINT REFERENCES public.residential_complexes(id) ON DELETE CASCADE NOT NULL,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABLA: DEPARTAMENTOS
CREATE TABLE IF NOT EXISTS public.apartments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  residential_complex_id BIGINT REFERENCES public.residential_complexes(id) ON DELETE CASCADE NOT NULL,
  apartment_block_id BIGINT REFERENCES public.apartment_blocks(id) ON DELETE SET NULL,
  number VARCHAR(50) NOT NULL,
  floor VARCHAR(20),
  resident_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  status VARCHAR(20) DEFAULT 'available' CHECK (status IN ('available', 'occupied', 'maintenance')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABLA: GUARDIAS
CREATE TABLE IF NOT EXISTS public.guards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  residential_complex_id BIGINT REFERENCES public.residential_complexes(id) ON DELETE CASCADE NOT NULL,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  shift VARCHAR(100) DEFAULT 'Turno Completo',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. TABLA: VISITANTES Y PASES DE ACCESO
CREATE TABLE IF NOT EXISTS public.visitors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  residential_complex_id BIGINT REFERENCES public.residential_complexes(id) ON DELETE CASCADE NOT NULL,
  code VARCHAR(20) NOT NULL,
  name VARCHAR(255) NOT NULL,
  document_number VARCHAR(50),
  phone VARCHAR(50),
  visiting_name VARCHAR(255) NOT NULL,
  apartment_number VARCHAR(50) NOT NULL,
  status VARCHAR(20) DEFAULT 'registered' CHECK (status IN ('registered', 'confirmed', 'in', 'out', 'rejected')),
  approved BOOLEAN DEFAULT TRUE,
  created_by UUID REFERENCES public.profiles(id),
  requested_by UUID REFERENCES public.profiles(id),
  check_in_at TIMESTAMPTZ,
  check_out_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. TABLA: COMUNICADOS
CREATE TABLE IF NOT EXISTS public.announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  residential_complex_id BIGINT REFERENCES public.residential_complexes(id) ON DELETE CASCADE NOT NULL,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  published_by UUID REFERENCES public.profiles(id),
  attachments JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. TABLA: COMENTARIOS REALTIME
CREATE TABLE IF NOT EXISTS public.announcement_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  announcement_id BIGINT REFERENCES public.announcements(id) ON DELETE CASCADE NOT NULL,
  residential_complex_id BIGINT REFERENCES public.residential_complexes(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id),
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. TABLA: INCIDENCIAS
CREATE TABLE IF NOT EXISTS public.incidents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  residential_complex_id BIGINT REFERENCES public.residential_complexes(id) ON DELETE CASCADE NOT NULL,
  reported_by UUID REFERENCES public.profiles(id),
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  priority VARCHAR(20) DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
  status VARCHAR(20) DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
  attachments JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. TABLA: RESERVAS
CREATE TABLE IF NOT EXISTS public.reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  residential_complex_id BIGINT REFERENCES public.residential_complexes(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id),
  area_name VARCHAR(100) NOT NULL,
  date DATE NOT NULL,
  start_time VARCHAR(20) NOT NULL,
  end_time VARCHAR(20) NOT NULL,
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. TABLA: NOTIFICACIONES
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id),
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  type VARCHAR(50),
  read BOOLEAN DEFAULT FALSE,
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. TABLA: AUDITORÍAS
CREATE TABLE IF NOT EXISTS public.audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  residential_complex_id BIGINT REFERENCES public.residential_complexes(id) ON DELETE SET NULL,
  action VARCHAR(100) NOT NULL,
  auditable_type VARCHAR(100) NOT NULL,
  auditable_id BIGINT,
  new_values JSONB,
  old_values JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- HABILITAR REALTIME EN LAS TABLAS ACTIVAS
ALTER PUBLICATION supabase_realtime ADD TABLE public.announcements;
ALTER PUBLICATION supabase_realtime ADD TABLE public.announcement_comments;
ALTER PUBLICATION supabase_realtime ADD TABLE public.visitors;
ALTER PUBLICATION supabase_realtime ADD TABLE public.incidents;
ALTER PUBLICATION supabase_realtime ADD TABLE public.reservations;
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;

-- BUCKETS DE ALMACENAMIENTO PARA FOTOS Y RECIBOS
INSERT INTO storage.buckets (id, name, public) VALUES ('face-photos', 'face-photos', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('payment-receipts', 'payment-receipts', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('incident-attachments', 'incident-attachments', true) ON CONFLICT (id) DO NOTHING;
`;

  return (
    <div className="space-y-6">
      <PageHeader
        title="Guía de Integración Supabase & Tiempo Real"
        subtitle="Documentación técnica, script SQL, estado de sincronización en vivo y checklist para producción"
        badge={
          isSupabaseLive ? (
            <Badge variant="emerald">🟢 Conectado a Supabase Realtime</Badge>
          ) : (
            <Badge variant="amber">🟡 Modo Local / Demo (Listo para Conectar)</Badge>
          )
        }
        actions={
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={handleTestPing}
              disabled={isTesting}
              icon={<RefreshCw className={`h-4 w-4 ${isTesting ? 'animate-spin' : ''}`} />}
            >
              {isTesting ? 'Probando...' : 'Verificar Conexión'}
            </Button>
            <Button
              variant="primary"
              size="sm"
              onClick={() => handleCopy(sqlCode, 'sql_header')}
              icon={<Copy className="h-4 w-4" />}
            >
              {copiedSection === 'sql_header' ? '¡SQL Copiado!' : 'Copiar Script SQL'}
            </Button>
          </div>
        }
      />

      {/* Connection Status Card */}
      <Card
        className={`border ${
          isSupabaseLive ? 'bg-emerald-950/20 border-emerald-800/60' : 'bg-slate-900 border-slate-800'
        } text-white shadow-xl`}
      >
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div
              className={`h-12 w-12 rounded-2xl flex items-center justify-center shrink-0 ${
                isSupabaseLive ? 'bg-emerald-500/20 text-emerald-400' : 'bg-slate-800 text-slate-400'
              }`}
            >
              <Database className="h-6 w-6" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-bold text-sm text-white">Estado de la Base de Datos</h3>
                <span
                  className={`inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-bold ${
                    isSupabaseLive
                      ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30'
                      : 'bg-amber-500/20 text-amber-300 border border-amber-500/30'
                  }`}
                >
                  {isSupabaseLive ? 'Supabase Activo' : 'Modo Demo Local'}
                </span>
              </div>
              <p className="text-xs text-slate-300 mt-0.5">
                {supabaseStatus?.message || 'Verificando conectividad con Supabase...'}
              </p>
              <span className="text-[10px] text-slate-500 block mt-1">
                URL Configurada: <code className="text-slate-400">{supabaseStatus?.url || 'Ninguna'}</code>
              </span>
            </div>
          </div>

          <div className="flex items-center gap-2 w-full sm:w-auto">
            <div className="p-3 bg-slate-950/70 rounded-xl border border-slate-800 text-xs w-full sm:w-auto">
              <span className="text-[10px] uppercase font-bold text-slate-400 block">Canales Realtime</span>
              <span className="font-bold text-emerald-400 flex items-center gap-1.5 mt-0.5">
                <Radio className="h-3.5 w-3.5 text-emerald-400 animate-pulse" />
                <span>postgres_changes Activo</span>
              </span>
            </div>
          </div>
        </div>
      </Card>

      {/* Navigation Tabs */}
      <div className="flex bg-slate-200/80 p-1 rounded-2xl text-xs font-semibold overflow-x-auto">
        <button
          onClick={() => setActiveTab('readme')}
          className={`py-2 px-4 rounded-xl transition-all whitespace-nowrap cursor-pointer ${
            activeTab === 'readme' ? 'bg-white text-slate-900 shadow-xs font-bold' : 'text-slate-600 hover:text-slate-900'
          }`}
        >
          📖 README & Arquitectura
        </button>
        <button
          onClick={() => setActiveTab('quick_setup')}
          className={`py-2 px-4 rounded-xl transition-all whitespace-nowrap cursor-pointer ${
            activeTab === 'quick_setup' ? 'bg-white text-slate-900 shadow-xs font-bold' : 'text-slate-600 hover:text-slate-900'
          }`}
        >
          ⚡ Paso a Paso (Cómo Conectar)
        </button>
        <button
          onClick={() => setActiveTab('sql')}
          className={`py-2 px-4 rounded-xl transition-all whitespace-nowrap cursor-pointer ${
            activeTab === 'sql' ? 'bg-white text-slate-900 shadow-xs font-bold' : 'text-slate-600 hover:text-slate-900'
          }`}
        >
          🐘 Script SQL Supabase
        </button>
        <button
          onClick={() => setActiveTab('realtime_checklist')}
          className={`py-2 px-4 rounded-xl transition-all whitespace-nowrap cursor-pointer ${
            activeTab === 'realtime_checklist' ? 'bg-white text-slate-900 shadow-xs font-bold' : 'text-slate-600 hover:text-slate-900'
          }`}
        >
          🔔 Checklist 100% Tiempo Real & Push
        </button>
      </div>

      {/* TAB CONTENT: README */}
      {activeTab === 'readme' && (
        <div className="space-y-6">
          <Card className="bg-white border-slate-200">
            <div className="prose prose-slate max-w-none text-xs leading-relaxed space-y-4">
              <div className="flex items-center gap-2 text-slate-900 font-bold text-base pb-3 border-b border-slate-200">
                <Layers className="h-5 w-5 text-emerald-600" />
                <span>Resumen de la Arquitectura del Sistema</span>
              </div>

              <p className="text-slate-600">
                <strong>Conjuntos App</strong> es una plataforma residencial multi-tenant diseñada para gestionar
                conjuntos residenciales, condominios cerrados y edificios inteligentes. Ofrece 4 roles independientes con
                permisos granulares:
              </p>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-3 not-prose my-4">
                <div className="p-3.5 rounded-xl border border-purple-200 bg-purple-50/60">
                  <span className="font-bold text-purple-900 text-xs flex items-center gap-1.5">
                    <span>👑</span> Super Admin (SaaS Global)
                  </span>
                  <p className="text-[11px] text-purple-800 mt-1">
                    Crea conjuntos, asigna códigos únicos (LP-YYYY-XXXX), gestiona planes de suscripción (Free, Pro,
                    Enterprise) y genera recibos de pago PDF descargables.
                  </p>
                </div>

                <div className="p-3.5 rounded-xl border border-emerald-200 bg-emerald-50/60">
                  <span className="font-bold text-emerald-900 text-xs flex items-center gap-1.5">
                    <span>🏢</span> Administrador de Conjunto
                  </span>
                  <p className="text-[11px] text-emerald-800 mt-1">
                    Aprobación de residentes con validación de fotografía facial, gestión de torres, departamentos,
                    cuotas, publicación de avisos con comentarios en vivo y supervisión de incidencias.
                  </p>
                </div>

                <div className="p-3.5 rounded-xl border border-sky-200 bg-sky-50/60">
                  <span className="font-bold text-sky-900 text-xs flex items-center gap-1.5">
                    <span>🏠</span> Residente
                  </span>
                  <p className="text-[11px] text-sky-800 mt-1">
                    Generación de pases QR / código para visitantes, reserva de áreas sociales (quincho, piscina),
                    reporte de averías con fotos y notificación sonora instantánea al ingresar una visita.
                  </p>
                </div>

                <div className="p-3.5 rounded-xl border border-amber-200 bg-amber-50/60">
                  <span className="font-bold text-amber-900 text-xs flex items-center gap-1.5">
                    <span>👮</span> Guardia de Garita
                  </span>
                  <p className="text-[11px] text-amber-800 mt-1">
                    Validador táctil de pases con tono acústico 880 Hz, registro de entradas/salidas (Check-In / Out) y
                    directorio telefónico instantáneo para emergencias.
                  </p>
                </div>
              </div>
            </div>
          </Card>
        </div>
      )}

      {/* TAB CONTENT: QUICK SETUP */}
      {activeTab === 'quick_setup' && (
        <div className="space-y-6">
          <Card className="bg-white border-slate-200">
            <h3 className="font-bold text-sm text-slate-900 mb-4 flex items-center gap-2">
              <Zap className="h-5 w-5 text-emerald-600" />
              <span>¿Cómo dejar lista la app con tu base de datos Supabase? (4 Pasos)</span>
            </h3>

            <div className="space-y-4">
              {/* Step 1 */}
              <div className="p-4 rounded-xl border border-slate-200 bg-slate-50/80 flex items-start gap-3">
                <span className="h-7 w-7 rounded-full bg-emerald-600 text-white font-bold text-xs flex items-center justify-center shrink-0">
                  1
                </span>
                <div className="flex-1">
                  <h4 className="text-xs font-bold text-slate-900">Crea tu proyecto en Supabase (Gratis)</h4>
                  <p className="text-xs text-slate-600 mt-0.5">
                    Entra a <a href="https://supabase.com" target="_blank" rel="noreferrer" className="text-emerald-600 underline font-semibold">supabase.com</a>, haz clic en <strong>New Project</strong>, asígnale un nombre (ej. <code>conjuntos-db</code>) y define tu contraseña.
                  </p>
                </div>
              </div>

              {/* Step 2 */}
              <div className="p-4 rounded-xl border border-slate-200 bg-slate-50/80 flex items-start gap-3">
                <span className="h-7 w-7 rounded-full bg-emerald-600 text-white font-bold text-xs flex items-center justify-center shrink-0">
                  2
                </span>
                <div className="flex-1">
                  <h4 className="text-xs font-bold text-slate-900">Pega y ejecuta el Script SQL</h4>
                  <p className="text-xs text-slate-600 mt-0.5">
                    En el menú lateral de Supabase, abre el <strong>SQL Editor</strong>, crea una nueva consulta, pega el código de la pestaña <strong>Script SQL Supabase</strong> y presiona <strong>Run</strong>.
                  </p>
                </div>
              </div>

              {/* Step 3 */}
              <div className="p-4 rounded-xl border border-slate-200 bg-slate-50/80 flex items-start gap-3">
                <span className="h-7 w-7 rounded-full bg-emerald-600 text-white font-bold text-xs flex items-center justify-center shrink-0">
                  3
                </span>
                <div className="flex-1">
                  <h4 className="text-xs font-bold text-slate-900">Copia tus credenciales API en las variables de entorno</h4>
                  <p className="text-xs text-slate-600 mt-0.5">
                    En Supabase ve a <strong>Project Settings ⚙️ &rarr; API</strong>. Copia la <strong>Project URL</strong> y la <strong>anon / public key</strong> en tu archivo <code>.env</code>:
                  </p>
                  <div className="bg-slate-950 p-3 rounded-lg font-mono text-[11px] text-emerald-400 mt-2 break-all">
                    VITE_SUPABASE_URL=https://kptuyksmdomgqntsdzsu.supabase.co<br />
                    VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwdHV5a3NtZG9tZ3FudHNkenN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc3OTg4ODQsImV4cCI6MjEwMzM3NDg4NH0.hGMnZHjG_IHJyCvgE67vPUGRV6WU7Nh2jfsTUcgkUcU<br />
                    EXPO_PUBLIC_SUPABASE_URL=https://kptuyksmdomgqntsdzsu.supabase.co<br />
                    EXPO_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwdHV5a3NtZG9tZ3FudHNkenN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc3OTg4ODQsImV4cCI6MjEwMzM3NDg4NH0.hGMnZHjG_IHJyCvgE67vPUGRV6WU7Nh2jfsTUcgkUcU
                  </div>
                </div>
              </div>

              {/* Step 4 */}
              <div className="p-4 rounded-xl border border-slate-200 bg-slate-50/80 flex items-start gap-3">
                <span className="h-7 w-7 rounded-full bg-emerald-600 text-white font-bold text-xs flex items-center justify-center shrink-0">
                  4
                </span>
                <div className="flex-1">
                  <h4 className="text-xs font-bold text-slate-900">¡Listo! La App sincronizará en tiempo real</h4>
                  <p className="text-xs text-slate-600 mt-0.5">
                    Al recargar la aplicación o hacer clic en <strong>Verificar Conexión</strong>, el badge cambiará a verde y todas las operaciones se persistirán en tu base de datos Supabase en tiempo real.
                  </p>
                </div>
              </div>
            </div>
          </Card>
        </div>
      )}

      {/* TAB CONTENT: SQL SCRIPT */}
      {activeTab === 'sql' && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <span className="text-xs text-slate-500">
              Script completo con 12 tablas, RLS, Storage Buckets y Realtime Publication.
            </span>
            <Button
              variant="primary"
              size="sm"
              onClick={() => handleCopy(sqlCode, 'sql_tab')}
              icon={<Copy className="h-3.5 w-3.5" />}
            >
              {copiedSection === 'sql_tab' ? '¡Copiado al Portapapeles!' : 'Copiar Script SQL'}
            </Button>
          </div>

          <Card noPadding className="bg-slate-950 border-slate-800 text-white overflow-hidden shadow-2xl">
            <div className="bg-slate-900/90 px-4 py-2.5 border-b border-slate-800 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="h-3 w-3 rounded-full bg-rose-500" />
                <span className="h-3 w-3 rounded-full bg-amber-500" />
                <span className="h-3 w-3 rounded-full bg-emerald-500" />
                <span className="ml-2 font-mono text-xs text-slate-400">schema_supabase_conjuntos.sql</span>
              </div>
            </div>
            <pre className="p-4 sm:p-6 overflow-x-auto font-mono text-xs text-emerald-400 leading-relaxed max-h-[580px] select-text">
              {sqlCode}
            </pre>
          </Card>
        </div>
      )}

      {/* TAB CONTENT: REALTIME CHECKLIST */}
      {activeTab === 'realtime_checklist' && (
        <div className="space-y-6">
          <Card className="bg-white border-slate-200">
            <h3 className="font-bold text-sm text-slate-900 mb-2 flex items-center gap-2">
              <Radio className="h-5 w-5 text-emerald-600" />
              <span>Checklist de Producción para Tiempo Real al 100%</span>
            </h3>
            <p className="text-xs text-slate-600 mb-6">
              Para que tu aplicación esté completamente lista en producción tanto en Web como en la App Móvil Android con notificaciones en segundo plano:
            </p>

            <div className="space-y-4">
              {/* Item 1 */}
              <div className="p-4 rounded-xl border border-emerald-200 bg-emerald-50/40 flex items-start gap-3">
                <CheckCircle2 className="h-5 w-5 text-emerald-600 shrink-0 mt-0.5" />
                <div>
                  <h4 className="text-xs font-bold text-emerald-950">1. Canales Realtime de Supabase (Listo en código ✅)</h4>
                  <p className="text-xs text-emerald-800 mt-1">
                    La aplicación ya incluye los listeners <code>supabase.channel()</code> para comentarios en avisos, validación de visitas por parte del guardia, nuevas incidencias y cambios de estado de reservas.
                  </p>
                </div>
              </div>

              {/* Item 2 */}
              <div className="p-4 rounded-xl border border-sky-200 bg-sky-50/40 flex items-start gap-3">
                <Smartphone className="h-5 w-5 text-sky-600 shrink-0 mt-0.5" />
                <div>
                  <h4 className="text-xs font-bold text-sky-950">2. Notificaciones Push Móviles con App Cerrada (FCM / Expo Push)</h4>
                  <p className="text-xs text-sky-800 mt-1">
                    Cuando un residente tiene el teléfono bloqueado o la app cerrada, los WebSockets de Supabase se suspenden por el sistema operativo Android. Para despertar el teléfono cuando el guardia valida el pase de visita, se utiliza un <strong>Database Webhook</strong> o <strong>Supabase Edge Function</strong> que dispara la notificación push a través de Expo Push API / Firebase Cloud Messaging usando el <code>fcm_token</code> guardado en la tabla <code>profiles</code>.
                  </p>
                </div>
              </div>

              {/* Item 3 */}
              <div className="p-4 rounded-xl border border-purple-200 bg-purple-50/40 flex items-start gap-3">
                <Shield className="h-5 w-5 text-purple-600 shrink-0 mt-0.5" />
                <div>
                  <h4 className="text-xs font-bold text-purple-950">3. Supabase Storage para Fotos Faciales y Evidencias</h4>
                  <p className="text-xs text-purple-800 mt-1">
                    El script SQL crea 3 buckets públicos (<code>face-photos</code>, <code>payment-receipts</code>, <code>incident-attachments</code>) para subir los archivos binarios directamente a Supabase Storage con URLs públicas optimizadas en CDN.
                  </p>
                </div>
              </div>
            </div>
          </Card>
        </div>
      )}
    </div>
  );
};
